FROM oven/bun AS build

WORKDIR /app

# Cache packages installation
COPY package.json package.json
COPY bun.lockb bun.lockb

RUN bun install

COPY ./drizzle ./drizzle
COPY ./src ./src

ENV NODE_ENV=production
ENV PORT=3002

RUN bun build \
  --compile \
  --minify-whitespace \
  --minify-syntax \
  --target bun \
  --outfile server \
  ./src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/drizzle drizzle
COPY --from=build /app/server server

ENV NODE_ENV=production
ENV PORT=3002

CMD ["./server"]

EXPOSE 3002